apiVersion: apps/v1
kind: Deployment
metadata:
  name: twse-weight-exporter
  labels:
    app: twse-weight-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twse-weight-exporter
  template:
    metadata:
      labels:
        app: twse-weight-exporter
    spec:
      containers:
        - name: twse-weight-exporter
          image: chaowen/twse-weight-portion-exporter:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twse-weight-exporter
  labels:
    app: twse-weight-exporter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: twse-weight-exporter